### ISSUE TITLE
ambiguous overload for 'operator=='

### ISSUE THREAD

**Issue by dimarusyy** [boostorg/system#61]
Applying `is_error_code_enum` for std::error_code emits compilation error:
https://godbolt.org/z/hzEP9n

This is a regression since boost-1.65.

**Comment by pdimov** [comment]
An interesting technique.

At this point I think I can only suggest a workaround on your side: define `operator==(boost::system::error_code e1, std::error_code e2)` with your desired semantics.

Boost.System can define this overload, but it won't have the behavior you want because it will convert e1 to std::error_code, not e2 to boost::system::error_code, and this won't match the pre-1.66 behavior of the comparison.
